routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


Route::get('/', function () {
    return redirect()->route("home");
});

Auth::routes([
    "reset" => false,// no pueden olvidar contraseña
]);

Route::get('/home', 'HomeController@index')->name('home');
// Permitir logout con petición get
Route::get("/logout", function () {
    Auth::logout();
    return redirect()->route("home");
})->name("logout");


Route::middleware("auth")
    ->group(function () {
        Route::resource("usuarios", "UserController")->parameters(["usuarios" => "user"]);
        Route::resource("empleados", "EmpleadosController");
        Route::resource("tipificacion", "TipificacionController");
    });

app/Empleado.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Empleado extends Model
{
    protected $table = "empleado";
    protected $fillable = ["idempleado", "nombre"];
}

app/Http/Controllers/EmpleadoController.php
<?php

namespace App\Http\Controllers;

use App\Empleado;
use Illuminate\Http\Request;

class EmpleadoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    
}

app/Http/Controllers/EmpleadosController.php
<?php

namespace App\Http\Controllers;
use DB;
use App\Premiosempleado;
use App\Empleado;
use App\Campania;
use Illuminate\Http\Request;
use Carbon\Carbon;

class EmpleadosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $premios = DB::table('premiosempleado')
            ->join('empleado', 'premiosempleado.idempleado', '=', 'empleado.idempleado')
            ->join('campania', 'premiosempleado.idcampania', '=', 'campania.idcampania')
            ->select('premiosempleado.*', 'empleado.nombre', 'campania.descripcion', 'tipificacion.tipificacion', 'premiosempleado.fechaRecojo')
            ->leftJoin("tipificacion", "premiosempleado.idpremio", "=", "tipificacion.idpremio")
            ->orderBy('tipificacion.fechaRegistro', 'desc')
            ->get();
        return view("empleados.empleados_index", ["premios" => $premios, "empleados" => Empleado::all()]);
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("empleados.empleados_create", ["empleados" => Empleado::all(), "campanias" => Campania::all()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $premio = new Premiosempleado($request->input());
        $premio->saveOrFail();
        return redirect()->route("empleados.index")->with("mensaje", "Premio empleado guardado");
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Premiosempleado $premiosempleado
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request)
    {
        $premios = DB::table('premiosempleado')
            ->join('empleado', 'premiosempleado.idempleado', '=', 'empleado.idempleado')
            ->join('campania', 'premiosempleado.idcampania', '=', 'campania.idcampania')
            ->select('premiosempleado.*', 'empleado.nombre', 'campania.descripcion', 'tipificacion.tipificacion', 'premiosempleado.fechaRecojo')
            ->leftJoin("tipificacion", "premiosempleado.idpremio", "=", "tipificacion.idpremio")
            ->where('premiosempleado.idempleado', $request->empleado)
            ->whereBetween('premiosempleado.fechaRecojo', [$request->fechaRegistroUno, $request->fechaRegistroDos])
            ->orderBy('tipificacion.fechaRegistro', 'desc')
            ->get();
        return view("empleados.empleados_index", ["premios" => $premios, "empleados" => Empleado::all()]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Premiosempleado $premiosempleado
     * @return \Illuminate\Http\Response
     */
    public function edit(string $idpremio)
    {
        $premio = DB::table('premiosempleado')
            ->join('empleado', 'premiosempleado.idempleado', '=', 'empleado.idempleado')
            ->join('campania', 'premiosempleado.idcampania', '=', 'campania.idcampania')
            ->select('premiosempleado.*', 'empleado.nombre', 'campania.descripcion')
            ->where('idpremio', $idpremio)
            ->first();
        return view("empleados.empleados_edit", ["premio" => $premio]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Premiosempleado $premiosempleado
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Premiosempleado $premiosempleado
     * @return \Illuminate\Http\Response
     */
    public function destroy(Premiosempleado $producto)
    {
    }
}

resources/views/empleados/empleados_create.blade.php
@extends("maestra")
@section("titulo", "Agregar premios empleados")
@section("contenido")
    <div class="row">
        <div class="col-12">
            <h1>Agregar premios empleados</h1>
            <form method="POST" action="{{route("empleados.store")}}">
                @csrf
                <div class="form-group">
                    <label class="label">Empleado</label>
                    <select required class="form-control" name="idempleado" id="idEmpleado">
                        @foreach($empleados as $emp)
                            <option value="{{$emp->idempleado}}">{{$emp->nombre}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label class="label">Campania</label>
                    <select required class="form-control" name="idcampania" id="idCampania">
                        @foreach($campanias as $camp)
                            <option value="{{$camp->idcampania}}">{{$camp->descripcion}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label class="label">Descripción Premio</label>
                    <input required autocomplete="off" name="descripcionPremio" class="form-control"
                           type="text" placeholder="Descripción">
                </div>
                <div class="form-group">
                    <label class="label">Lugar de Recojo</label>
                    <input required autocomplete="off" name="lugarPrestacion" class="form-control"
                           type="text" placeholder="Precio de compra">
                </div>
                <div class="form-group">
                    <label class="label">Fecha de Recojo</label>
                    <input required autocomplete="off" name="fechaRecojo" class="form-control"
                           type="date" placeholder="Precio de venta">
                </div>
                <div class="form-group">
                    <label class="label">Fecha de Vencimiento</label>
                    <input required autocomplete="off" name="fechaVencimiento" class="form-control"
                           type="date" placeholder="Precio de venta">
                </div>

                @include("notificacion")
                <button class="btn btn-success">Guardar</button>
                <a class="btn btn-primary" href="{{route("empleados.index")}}">Volver al listado</a>
            </form>
        </div>
    </div>
@endsection

resources/views/empleados/empleados_edit.blade.php
@extends("maestra")
@section("titulo", "Formulario de Tipificaciones - premio empleado")
@section("contenido")
    <div class="row">
        <div class="col-12">
            <h1>Formulario de Tipificaciones</h1>
                <div class="form-group">
                    <label class="label">Empleado</label>
                    <input required value="{{$premio->nombre}}" autocomplete="off" name="codigo_barras"
                           class="form-control" readonly
                           type="text" placeholder="Código de barras">
                </div>
                <div class="form-group">
                    <label class="label">Campania</label>
                    <input required value="{{$premio->descripcion}}" autocomplete="off" name="codigo_barras"
                           class="form-control" readonly
                           type="text" placeholder="Código de barras">
                </div>
                <div class="form-group">
                    <label class="label">Descripción Premio</label>
                    <input required value="{{$premio->descripcionPremio}}" autocomplete="off" name="descripcion"
                           class="form-control" readonly
                           type="text" placeholder="Descripción">
                </div>
                <div class="form-group">
                    <label class="label">Lugar de Recojo</label>
                    <input required value="{{$premio->lugarPrestacion}}" autocomplete="off" name="precio_compra"
                           class="form-control" readonly
                           type="text" placeholder="Precio de compra">
                </div>
                <div class="form-group">
                    <label class="label">Fecha de Recojo</label>
                    <input required value="{{$premio->fechaRecojo}}" autocomplete="off" name="precio_venta"
                           class="form-control" readonly
                           type="date" placeholder="Precio de venta">
                </div>
                <div class="form-group">
                    <label class="label">Fecha de Vencimiento</label>
                    <input required value="{{$premio->fechaVencimiento}}" autocomplete="off" name="existencia"
                           class="form-control" readonly
                           type="date" placeholder="Existencia">
                </div>
            <form method="POST" action="{{route("tipificacion.store")}}">
                @csrf
                <div class="form-group">
                    <input hidden autocomplete="off" name="idpremio" class="form-control"
                           type="text" value="{{ $premio->idpremio}}">
                </div>

                <div class="form-group">
                    <label class="label">Tipificacion</label>
                    <select required class="form-control" name="tipificacion" id="tipificacion">
                        <option value="1">Informado correctamente</option>
                        <option value="2">No informado</option>
                        <option value="3">Nuevo </option>
                    </select>
                </div>

                <div class="form-group">
                    <input hidden autocomplete="off" name="fechaRegistro" class="form-control"
                           type="text" value="{{ date('Y-m-d') }}">
                </div>

                <div class="form-group">
                    <label class="label">Observacion</label>
                    <input required autocomplete="off" name="observacion" class="form-control"
                           class="form-control"
                           type="text" placeholder="observacion">
                </div>

                @include("notificacion")
                <button class="btn btn-success">Guardar</button>
                <a class="btn btn-primary" href="{{route("empleados.index")}}">Volver</a>
            </form>
        </div>
    </div>
@endsection

resources/views/empleados/empleados_index.blade.php
@extends("maestra")
@section("titulo", "Premios Empleados")
@section("contenido")
    <div class="row">
        <div class="col-12">
            <h1>Premios Empleados <i class="fa fa-box"></i></h1>
            <a href="{{route("empleados.create")}}" class="btn btn-success mb-2">Agregar</a>
            <form method="GET" action="{{route("empleados.show", 'show')}}">
                @csrf
                <div class="form-group col-md-12">
                    <div class="col-md-3">
                        <label class="label">Nombre Empleado</label>
                        <select required class="form-control" name="empleado" id="empleado">
                            @foreach($empleados as $emp)
                                <option value="{{$emp->idempleado}}">{{$emp->nombre}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="col-md-3">
                        <label class="label">Fecha de Registro</label>
                        <input autocomplete="off" name="fechaRegistroUno" class="form-control"
                            type="date">
                    </div>
                    <div class="col-md-3">
                        <input autocomplete="off" name="fechaRegistroDos" class="form-control"
                            type="date">
                    </div>
                </div>
                <button class="btn btn-danger">Buscar</button>
            </form>
            @include("notificacion")
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Empleado</th>
                        <th>Descripción del premio</th>
                        <th>Campania</th>
                        <th>Fecha de recojo</th>
                        <th>Lugar de recojo</th>
                        <th>Fecha de vencimiento</th>

                        <th>Tipificacion</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($premios as $premio)
                        <tr>
                            <td>{{$premio->idpremio}}</td>
                            <td>{{$premio->nombre}}</td>
                            <td>{{$premio->descripcionPremio}}</td>
                            <td>{{$premio->descripcion}}</td>
                            <td>{{$premio->fechaRecojo}}</td>
                            <td>{{$premio->lugarPrestacion}}</td>
                            <td>{{$premio->fechaVencimiento}}</td>
                            <td>
                                <a class="btn btn-warning" href="{{route("empleados.edit",[$premio->idpremio])}}">
                                    Seguimiento
                                </a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection